-- DROP TABLE IF EXISTS CITY;
--
-- create table USER
-- (
--     user_id  bigint auto_increment primary key,
--     username varchar(128) not null unique,
--     password varchar(256) not null
-- );
